kind: Service
apiVersion: v1
metadata:
  name: alta-api-docker
  labels:
    app: alta-api-docker
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: alta-api-docker
  type: LoadBalancer