kind: Deployment
apiVersion: apps/v1
metadata:
  name: alta-api-docker
  labels:
    app: alta-api-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alta-api-docker
  template:
    metadata:
      labels:
        app: alta-api-docker
    spec:
      containers:
        - image: docker.io/urnikrokhiyah/alta-api-docker:latest
          name: alta-api-docker
          resources:
            limits:
              memory: 200Mi
              cpu: 1
            requests:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 8080
              name: http-server